### ISSUE TITLE
Graphs not showing last entry until flipped

### ISSUE THREAD

**Issue by bethmo** [BlueHerons/StatTracker#39] opened 2015-01-13 08:57 UTC
Very odd bug.  Tonight all of my 30-day graphs except for Missions and Hacks are showing the data only up through yesterday's entry.  Clicking the "This week" button shows the data including today, and then clicking back on the "Past 30 days" to swap back to the 30-day graph DOES include today's.  Refreshing the page puts it back to the missing-today version.
The Missions and Hacks graphs are correct without clicking.

**Comment by johnluetke** [comment] 2015-01-13 15:30
Are you able to reproduce consistently?

Sounds like a caching glitch

**Comment by johnluetke** [comment] 2015-01-16 23:00
Closing due to lack of extra information

**Closed by johnluetke** 2015-01-16 23:00 UTC
Labels: invalid
